version: '3.8'

services:
  database: #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: database_cars
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=helder
      - POSTGRES_PASSWORD=postgrescars
      - POSTGRES_DB=cars
    volumes:
      - pgdata:/data/mydbpostgres
  app:
    container_name: cars
    build: . #o mesmo que: docker build -t cars .
    restart: always
    command: yarn dev #incluído para fazer testes.
    ports:
      - 3333:3333
      - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
    volumes:
      - .:/usr/app
    links: # faz uma ligação entre os containers, permitindo que o container de destino (api) tenha informações do container de origem(database). 
      - database
    depends_on: #informar que nosso serviço de api irá depender do serviço do banco de dados (database). Agora a comunicação é feita pelo nome do container (não mais por IP).
      - database

volumes:
  pgdata:
    driver: local